### ISSUE TITLE
Add a section about your victories.

### ISSUE THREAD

**Issue by supunTE** [gothira/portfolio#3]
Add a section about your victories. As an example you won bits 2018. Add it there and add a shott description about BITS 2018.

**Comment by gothira** [comment]
See now

**Comment by supunTE** [comment]
Add details, 
![image](https://user-images.githubusercontent.com/33794760/60809330-0c08ed00-a1a8-11e9-890e-057bd61093ee.png)

Add the github pages link in the description,
![image](https://user-images.githubusercontent.com/33794760/60809398-322e8d00-a1a8-11e9-8e3b-8e5a91893d6b.png)

**Comment by gothira** [comment]
completed
